import type { Business, Customer, FeedbackItem, AnalyticsData } from "@/types";

// ===== KINGS CUTS LONDON =====
export const kingsCutsBusiness: Business = {
  id: "demo-kings-cuts",
  name: "Kings Cuts London",
  ownerName: "Marcus Johnson",
  email: "marcus@kingscuts.co.uk",
  phone: "+44 7911 234567",
  address: "142 Shoreditch High Street, London E1 6JE",
  googleReviewLink: "https://g.page/r/kings-cuts-london/review",
  brandColor: "#0EA5E9",
  plan: "annual",
  forwardingEmail: "kings-cuts-4x7k@bookings.vomni.app",
  smsTemplate:
    "Hi {name}! Thanks for coming in today. Could you spare 30 seconds to share your experience? It really helps us grow 🙏 {link}",
  reviewRequestDelay: 4,
  quietHoursStart: 22,
  quietHoursEnd: 8,
  notifyOnNegative: true,
  notifyEmail: "marcus@kingscuts.co.uk",
  onboardingComplete: true,
  onboardingSteps: [true, true, true, true, true],
  createdAt: "2025-09-15T10:00:00Z",
  timezone: "Europe/London",
};

export const kingsCutsCustomers: Customer[] = [
  {
    id: "kc-1",
    businessId: "demo-kings-cuts",
    name: "James Mitchell",
    phone: "+44 7700 900001",
    email: "james.m@email.com",
    bookingDate: "2026-03-24",
    bookingTime: "10:00",
    service: "Skin Fade + Beard Trim",
    staffMember: "Marcus",
    parsingConfidence: 98,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-24T14:00:00Z",
    reviewRequestOpenedAt: "2026-03-24T14:08:00Z",
    reviewRequestClickedAt: "2026-03-24T14:09:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-24T14:09:30Z",
    createdAt: "2026-03-24T10:00:00Z",
  },
  {
    id: "kc-2",
    businessId: "demo-kings-cuts",
    name: "James Smith",
    phone: "+44 7700 900002",
    email: "james.s@email.com",
    bookingDate: "2026-03-24",
    bookingTime: "11:30",
    service: "Caesar Cut",
    staffMember: "Deon",
    parsingConfidence: 96,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-24T15:30:00Z",
    reviewRequestOpenedAt: "2026-03-24T15:42:00Z",
    reviewRequestClickedAt: "2026-03-24T15:43:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-24T15:43:45Z",
    createdAt: "2026-03-24T11:30:00Z",
  },
  {
    id: "kc-3",
    businessId: "demo-kings-cuts",
    name: "Tyler Brooks",
    phone: "+44 7700 900003",
    email: "tyler.b@email.com",
    bookingDate: "2026-03-23",
    bookingTime: "14:00",
    service: "Taper Fade",
    staffMember: "Marcus",
    parsingConfidence: 94,
    parseStatus: "success",
    reviewRequestStatus: "private_feedback",
    reviewRequestSentAt: "2026-03-23T18:00:00Z",
    reviewRequestOpenedAt: "2026-03-23T18:15:00Z",
    rating: 2,
    feedbackId: "fb-1",
    createdAt: "2026-03-23T14:00:00Z",
  },
  {
    id: "kc-4",
    businessId: "demo-kings-cuts",
    name: "Rahul Sharma",
    phone: "+44 7700 900004",
    email: "rahul.s@email.com",
    bookingDate: "2026-03-23",
    bookingTime: "09:30",
    service: "Skin Fade",
    staffMember: "Deon",
    parsingConfidence: 99,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-23T13:30:00Z",
    reviewRequestOpenedAt: "2026-03-23T13:50:00Z",
    reviewRequestClickedAt: "2026-03-23T13:51:00Z",
    rating: 4,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-23T13:51:30Z",
    createdAt: "2026-03-23T09:30:00Z",
  },
  {
    id: "kc-5",
    businessId: "demo-kings-cuts",
    name: "Callum Wright",
    phone: "+44 7700 900005",
    email: "callum.w@email.com",
    bookingDate: "2026-03-22",
    bookingTime: "16:00",
    service: "Classic Cut + Hot Towel Shave",
    staffMember: "Marcus",
    parsingConfidence: 97,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-22T20:00:00Z",
    reviewRequestOpenedAt: "2026-03-22T20:12:00Z",
    reviewRequestClickedAt: "2026-03-22T20:13:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-22T20:13:20Z",
    createdAt: "2026-03-22T16:00:00Z",
  },
  {
    id: "kc-6",
    businessId: "demo-kings-cuts",
    name: "Ben Harris",
    phone: "+44 7700 900006",
    email: "ben.h@email.com",
    bookingDate: "2026-03-22",
    bookingTime: "13:00",
    service: "Skin Fade",
    staffMember: "Jordan",
    parsingConfidence: 92,
    parseStatus: "success",
    reviewRequestStatus: "sent",
    reviewRequestSentAt: "2026-03-22T17:00:00Z",
    createdAt: "2026-03-22T13:00:00Z",
  },
  {
    id: "kc-7",
    businessId: "demo-kings-cuts",
    name: "Mateo Rodriguez",
    phone: "+44 7700 900007",
    email: "mateo.r@email.com",
    bookingDate: "2026-03-21",
    bookingTime: "11:00",
    service: "Beard Shaping",
    staffMember: "Deon",
    parsingConfidence: 95,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-21T15:00:00Z",
    reviewRequestOpenedAt: "2026-03-21T15:22:00Z",
    reviewRequestClickedAt: "2026-03-21T15:23:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-21T15:23:40Z",
    createdAt: "2026-03-21T11:00:00Z",
  },
  {
    id: "kc-8",
    businessId: "demo-kings-cuts",
    name: "Noah Patel",
    phone: "+44 7700 900008",
    email: "noah.p@email.com",
    bookingDate: "2026-03-21",
    bookingTime: "15:30",
    service: "Taper + Line Up",
    staffMember: "Marcus",
    parsingConfidence: 93,
    parseStatus: "success",
    reviewRequestStatus: "opened",
    reviewRequestSentAt: "2026-03-21T19:30:00Z",
    reviewRequestOpenedAt: "2026-03-21T20:45:00Z",
    createdAt: "2026-03-21T15:30:00Z",
  },
  {
    id: "kc-9",
    businessId: "demo-kings-cuts",
    name: "Luca Ferrari",
    phone: "+44 7700 900009",
    email: "luca.f@email.com",
    bookingDate: "2026-03-20",
    bookingTime: "12:00",
    service: "Skin Fade + Beard Trim",
    staffMember: "Jordan",
    parsingConfidence: 98,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-20T16:00:00Z",
    reviewRequestOpenedAt: "2026-03-20T16:08:00Z",
    reviewRequestClickedAt: "2026-03-20T16:09:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-20T16:09:15Z",
    createdAt: "2026-03-20T12:00:00Z",
  },
  {
    id: "kc-10",
    businessId: "demo-kings-cuts",
    name: "Aiden Clarke",
    phone: "+44 7700 900010",
    email: "aiden.c@email.com",
    bookingDate: "2026-03-20",
    bookingTime: "10:00",
    service: "Classic Cut",
    staffMember: "Deon",
    parsingConfidence: 96,
    parseStatus: "success",
    reviewRequestStatus: "private_feedback",
    reviewRequestSentAt: "2026-03-20T14:00:00Z",
    reviewRequestOpenedAt: "2026-03-20T16:30:00Z",
    rating: 3,
    feedbackId: "fb-2",
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "kc-11",
    businessId: "demo-kings-cuts",
    name: "Samuel Green",
    phone: "+44 7700 900011",
    email: "samuel.g@email.com",
    bookingDate: "2026-03-19",
    bookingTime: "14:00",
    service: "Skin Fade",
    staffMember: "Marcus",
    parsingConfidence: 99,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-19T18:00:00Z",
    reviewRequestOpenedAt: "2026-03-19T18:22:00Z",
    reviewRequestClickedAt: "2026-03-19T18:23:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-19T18:23:30Z",
    createdAt: "2026-03-19T14:00:00Z",
  },
  {
    id: "kc-12",
    businessId: "demo-kings-cuts",
    name: "David Kim",
    phone: "+44 7700 900012",
    email: "david.k@email.com",
    bookingDate: "2026-03-19",
    bookingTime: "09:00",
    service: "Taper Fade + Beard",
    staffMember: "Jordan",
    parsingConfidence: 94,
    parseStatus: "success",
    reviewRequestStatus: "failed",
    reviewRequestSentAt: "2026-03-19T13:00:00Z",
    createdAt: "2026-03-19T09:00:00Z",
  },
  {
    id: "kc-13",
    businessId: "demo-kings-cuts",
    name: "Antoine Dubois",
    phone: "+44 7700 900013",
    email: "antoine.d@email.com",
    bookingDate: "2026-03-18",
    bookingTime: "13:30",
    service: "Skin Fade",
    staffMember: "Deon",
    parsingConfidence: 97,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-18T17:30:00Z",
    reviewRequestOpenedAt: "2026-03-18T17:45:00Z",
    reviewRequestClickedAt: "2026-03-18T17:46:00Z",
    rating: 4,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-18T17:46:20Z",
    createdAt: "2026-03-18T13:30:00Z",
  },
  {
    id: "kc-14",
    businessId: "demo-kings-cuts",
    name: "Ethan Williams",
    phone: "+44 7700 900014",
    email: "ethan.w@email.com",
    bookingDate: "2026-03-17",
    bookingTime: "16:30",
    service: "Caesar Cut",
    staffMember: "Marcus",
    parsingConfidence: 95,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-17T20:30:00Z",
    reviewRequestOpenedAt: "2026-03-17T20:44:00Z",
    reviewRequestClickedAt: "2026-03-17T20:45:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-17T20:45:30Z",
    createdAt: "2026-03-17T16:30:00Z",
  },
  {
    id: "kc-15",
    businessId: "demo-kings-cuts",
    name: "Isaac Thompson",
    phone: "+44 7700 900015",
    email: "isaac.t@email.com",
    bookingDate: "2026-03-17",
    bookingTime: "11:00",
    service: "Hot Towel Shave",
    staffMember: "Jordan",
    parsingConfidence: 98,
    parseStatus: "success",
    reviewRequestStatus: "private_feedback",
    reviewRequestSentAt: "2026-03-17T15:00:00Z",
    reviewRequestOpenedAt: "2026-03-17T19:22:00Z",
    rating: 2,
    feedbackId: "fb-3",
    createdAt: "2026-03-17T11:00:00Z",
  },
];

export const kingsCutsFeedback: FeedbackItem[] = [
  {
    id: "fb-1",
    businessId: "demo-kings-cuts",
    customerId: "kc-3",
    customerName: "Tyler Brooks",
    customerPhone: "+44 7700 900003",
    rating: 2,
    feedback:
      "The fade was uneven on the left side. I pointed it out and felt like it wasn't really addressed properly. Not what I expected for the price.",
    status: "in_progress",
    aiSuggestedReply:
      "Hi Tyler, I'm really sorry to hear that. An uneven fade that wasn't fixed when you raised it is exactly the kind of thing we should never let leave the shop. That's on us, not you. I'd love to have you back in so we can make it right - no charge, of course. Just reply to this or call 07911 234567 and we'll sort a time. - Marcus at Kings Cuts",
    aiReplies: {
      apologetic: "Hi Tyler, I'm really sorry to hear that. An uneven fade that wasn't fixed when you raised it is exactly the kind of thing we should never let leave the shop. That's on us, not you. I'd love to have you back in so we can make it right - no charge, of course. Just reply to this or call 07911 234567 and we'll sort a time. - Marcus at Kings Cuts",
      professional: "Hi Tyler, thank you for letting us know. An uneven finish is below the standard we hold ourselves to, and I understand your frustration when it wasn't corrected on the day. We'd like to make this right - please call us on 07911 234567 or reply here to book a complimentary visit at your convenience. - Kings Cuts",
      personal: "Tyler - honestly, gutted to hear this. An uneven fade is one thing, but not being listened to when you flagged it? That's not us. Come back in, ask for Marcus, and I'll sort it personally. On the house. - Marcus",
    },
    internalNotes: "Spoke with Deon - he remembers the cut. Will address technique.",
    createdAt: "2026-03-23T18:15:00Z",
  },
  {
    id: "fb-2",
    businessId: "demo-kings-cuts",
    customerId: "kc-10",
    customerName: "Aiden Clarke",
    customerPhone: "+44 7700 900010",
    rating: 3,
    feedback:
      "Wait was longer than expected - I was kept waiting 20 mins past my appointment. Cut itself was fine but the wait put me off.",
    status: "resolved",
    aiSuggestedReply:
      "Hi Aiden, I'm really sorry about the wait - 20 minutes past your appointment is genuinely not good enough. Your time matters and we didn't respect that. We're working on our scheduling to make sure this doesn't happen again. I'd love to give you a better experience - your next cut is on us. Just mention this when you book. - Marcus",
    aiReplies: {
      apologetic: "Hi Aiden, I'm really sorry about the wait - 20 minutes past your appointment is genuinely not good enough. Your time matters and we didn't respect that. We're working on our scheduling to make sure this doesn't happen again. I'd love to give you a better experience - your next cut is on us. Just mention this when you book. - Marcus",
      professional: "Hi Aiden, thank you for the feedback. A 20-minute delay past your appointment time is not the standard we operate to, and I appreciate you flagging it. As a gesture of goodwill, your next visit will be complimentary - please mention this when booking. We are actively reviewing our scheduling processes. - Kings Cuts",
      personal: "Aiden - 20 mins over? That's rough, especially when you've planned your day around it. Totally fair to be put off. Next one's on us - just mention it when you book and I'll make sure you're in and out on time. - Marcus",
    },
    internalNotes: "Resolved - offered free cut. Aiden replied and accepted.",
    resolvedAt: "2026-03-21T10:00:00Z",
    resolution: "Offered complimentary cut on next visit. Customer accepted.",
    createdAt: "2026-03-20T16:30:00Z",
  },
  {
    id: "fb-3",
    businessId: "demo-kings-cuts",
    customerId: "kc-15",
    customerName: "Isaac Thompson",
    customerPhone: "+44 7700 900015",
    rating: 2,
    feedback:
      "Hot towel shave nicked my chin twice. Felt rushed. The barber seemed distracted. Skin was irritated for two days after.",
    status: "new",
    aiSuggestedReply:
      "Hi Isaac, I'm genuinely sorry - a nick during a shave is uncomfortable at the best of times, but skin irritation for two days afterwards is not acceptable. That's not a standard we can stand behind. I'd like to speak with you directly. Please call me, Marcus, on 07911 234567 - I'd like to personally make this right, whether that's a refund, a complimentary service, or just a conversation. Thank you for telling us.",
    aiReplies: {
      apologetic: "Hi Isaac, I'm genuinely sorry - a nick during a shave is uncomfortable at the best of times, but skin irritation for two days afterwards is not acceptable. That's not a standard we can stand behind. I'd like to speak with you directly. Please call me, Marcus, on 07911 234567 - I'd like to personally make this right, whether that's a refund, a complimentary service, or just a conversation. Thank you for telling us.",
      professional: "Hi Isaac, thank you for bringing this to our attention. A nick resulting in two days of skin irritation is below the standard we hold, and I understand how unpleasant that experience must have been. Please call us on 07911 234567 so we can discuss how to resolve this for you. We take all feedback of this nature seriously. - Kings Cuts",
      personal: "Isaac - I'm really sorry. That shouldn't have happened, full stop. Two days of irritation from a shave here is not something I can brush off. Call me directly on 07911 234567 - I'm Marcus, the owner - and let's sort this properly. Refund, free service, whatever you need. - Marcus",
    },
    createdAt: "2026-03-17T19:22:00Z",
  },
];

export const kingsCutsAnalytics: AnalyticsData[] = [
  { month: "Oct 2025", sent: 28, completed: 14, redirected: 11, negativeCaught: 1, avgRating: 3.9 },
  { month: "Nov 2025", sent: 31, completed: 17, redirected: 13, negativeCaught: 1, avgRating: 4.0 },
  { month: "Dec 2025", sent: 35, completed: 20, redirected: 16, negativeCaught: 2, avgRating: 4.1 },
  { month: "Jan 2026", sent: 38, completed: 23, redirected: 19, negativeCaught: 1, avgRating: 4.2 },
  { month: "Feb 2026", sent: 43, completed: 27, redirected: 23, negativeCaught: 2, avgRating: 4.2 },
  { month: "Mar 2026", sent: 47, completed: 31, redirected: 28, negativeCaught: 3, avgRating: 4.3 },
];

// ===== BELLA VISTA RESTAURANT =====
export const bellaVistaBusiness: Business = {
  id: "demo-bella-vista",
  name: "Bella Vista Restaurant",
  ownerName: "Sofia Rossi",
  email: "sofia@bellavista.com",
  phone: "+1 (212) 555-0187",
  address: "88 West 34th Street, New York, NY 10001",
  googleReviewLink: "https://g.page/r/bella-vista-nyc/review",
  brandColor: "#0EA5E9",
  plan: "monthly",
  forwardingEmail: "bella-vista-9m2p@bookings.vomni.app",
  smsTemplate:
    "Hi {name}! Thank you so much for dining with us tonight. We'd love to hear about your experience — takes 30 seconds: {link}",
  reviewRequestDelay: 3,
  quietHoursStart: 22,
  quietHoursEnd: 8,
  notifyOnNegative: true,
  notifyEmail: "sofia@bellavista.com",
  onboardingComplete: true,
  onboardingSteps: [true, true, true, true, true],
  createdAt: "2026-01-08T10:00:00Z",
  timezone: "America/New_York",
};

export const bellaVistaCustomers: Customer[] = [
  {
    id: "bv-1",
    businessId: "demo-bella-vista",
    name: "Michael Chen",
    phone: "+1 212 555 0201",
    email: "michael.c@email.com",
    bookingDate: "2026-03-24",
    bookingTime: "19:00",
    service: "Dinner reservation (2 guests)",
    staffMember: "Evening team",
    parsingConfidence: 96,
    parseStatus: "success",
    reviewRequestStatus: "scheduled",
    createdAt: "2026-03-24T19:00:00Z",
  },
  {
    id: "bv-2",
    businessId: "demo-bella-vista",
    name: "Jennifer Walsh",
    phone: "+1 212 555 0202",
    email: "jennifer.w@email.com",
    bookingDate: "2026-03-24",
    bookingTime: "20:00",
    service: "Dinner reservation (4 guests)",
    staffMember: "Evening team",
    parsingConfidence: 94,
    parseStatus: "success",
    reviewRequestStatus: "scheduled",
    createdAt: "2026-03-24T20:00:00Z",
  },
  {
    id: "bv-3",
    businessId: "demo-bella-vista",
    name: "David Okafor",
    phone: "+1 212 555 0203",
    email: "david.o@email.com",
    bookingDate: "2026-03-23",
    bookingTime: "19:30",
    service: "Dinner reservation (2 guests)",
    staffMember: "Evening team",
    parsingConfidence: 97,
    parseStatus: "success",
    reviewRequestStatus: "sent",
    reviewRequestSentAt: "2026-03-23T22:30:00Z",
    createdAt: "2026-03-23T19:30:00Z",
  },
  {
    id: "bv-4",
    businessId: "demo-bella-vista",
    name: "Rachel Kim",
    phone: "+1 212 555 0204",
    email: "rachel.k@email.com",
    bookingDate: "2026-03-23",
    bookingTime: "18:00",
    service: "Dinner reservation (6 guests)",
    staffMember: "Evening team",
    parsingConfidence: 93,
    parseStatus: "success",
    reviewRequestStatus: "private_feedback",
    reviewRequestSentAt: "2026-03-23T21:00:00Z",
    reviewRequestOpenedAt: "2026-03-23T21:18:00Z",
    rating: 1,
    feedbackId: "bv-fb-1",
    createdAt: "2026-03-23T18:00:00Z",
  },
  {
    id: "bv-5",
    businessId: "demo-bella-vista",
    name: "Thomas Laurent",
    phone: "+1 212 555 0205",
    email: "thomas.l@email.com",
    bookingDate: "2026-03-22",
    bookingTime: "20:30",
    service: "Dinner reservation (2 guests)",
    staffMember: "Evening team",
    parsingConfidence: 98,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-22T23:30:00Z",
    reviewRequestOpenedAt: "2026-03-23T08:12:00Z",
    reviewRequestClickedAt: "2026-03-23T08:13:00Z",
    rating: 4,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-23T08:13:30Z",
    createdAt: "2026-03-22T20:30:00Z",
  },
  {
    id: "bv-6",
    businessId: "demo-bella-vista",
    name: "Priya Nair",
    phone: "+1 212 555 0206",
    email: "priya.n@email.com",
    bookingDate: "2026-03-21",
    bookingTime: "19:00",
    service: "Dinner reservation (2 guests)",
    staffMember: "Evening team",
    parsingConfidence: 95,
    parseStatus: "success",
    reviewRequestStatus: "opened",
    reviewRequestSentAt: "2026-03-21T22:00:00Z",
    reviewRequestOpenedAt: "2026-03-21T22:34:00Z",
    createdAt: "2026-03-21T19:00:00Z",
  },
  {
    id: "bv-7",
    businessId: "demo-bella-vista",
    name: "Carlos Mendez",
    phone: "+1 212 555 0207",
    email: "carlos.m@email.com",
    bookingDate: "2026-03-21",
    bookingTime: "20:00",
    service: "Dinner reservation (4 guests)",
    staffMember: "Evening team",
    parsingConfidence: 91,
    parseStatus: "success",
    reviewRequestStatus: "private_feedback",
    reviewRequestSentAt: "2026-03-21T23:00:00Z",
    reviewRequestOpenedAt: "2026-03-21T23:25:00Z",
    rating: 2,
    feedbackId: "bv-fb-2",
    createdAt: "2026-03-21T20:00:00Z",
  },
  {
    id: "bv-8",
    businessId: "demo-bella-vista",
    name: "Emily Foster",
    phone: "+1 212 555 0208",
    email: "emily.f@email.com",
    bookingDate: "2026-03-20",
    bookingTime: "18:30",
    service: "Dinner reservation (2 guests)",
    staffMember: "Evening team",
    parsingConfidence: 97,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-20T21:30:00Z",
    reviewRequestOpenedAt: "2026-03-20T21:48:00Z",
    reviewRequestClickedAt: "2026-03-20T21:49:00Z",
    rating: 5,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-20T21:49:20Z",
    createdAt: "2026-03-20T18:30:00Z",
  },
  {
    id: "bv-9",
    businessId: "demo-bella-vista",
    name: "Alex Novak",
    phone: "+1 212 555 0209",
    email: "alex.n@email.com",
    bookingDate: "2026-03-19",
    bookingTime: "19:30",
    service: "Dinner reservation (3 guests)",
    staffMember: "Evening team",
    parsingConfidence: 94,
    parseStatus: "success",
    reviewRequestStatus: "sent",
    reviewRequestSentAt: "2026-03-19T22:30:00Z",
    createdAt: "2026-03-19T19:30:00Z",
  },
  {
    id: "bv-10",
    businessId: "demo-bella-vista",
    name: "Samantha Hoang",
    phone: "+1 212 555 0210",
    email: "sam.h@email.com",
    bookingDate: "2026-03-19",
    bookingTime: "20:30",
    service: "Dinner reservation (2 guests)",
    staffMember: "Evening team",
    parsingConfidence: 98,
    parseStatus: "success",
    reviewRequestStatus: "private_feedback",
    reviewRequestSentAt: "2026-03-19T23:30:00Z",
    reviewRequestOpenedAt: "2026-03-19T23:48:00Z",
    rating: 2,
    feedbackId: "bv-fb-3",
    createdAt: "2026-03-19T20:30:00Z",
  },
  {
    id: "bv-11",
    businessId: "demo-bella-vista",
    name: "James O'Brien",
    phone: "+1 212 555 0211",
    email: "james.o@email.com",
    bookingDate: "2026-03-18",
    bookingTime: "19:00",
    service: "Dinner reservation (2 guests)",
    staffMember: "Evening team",
    parsingConfidence: 92,
    parseStatus: "success",
    reviewRequestStatus: "failed",
    createdAt: "2026-03-18T19:00:00Z",
  },
  {
    id: "bv-12",
    businessId: "demo-bella-vista",
    name: "Nina Rodriguez",
    phone: "+1 212 555 0212",
    email: "nina.r@email.com",
    bookingDate: "2026-03-17",
    bookingTime: "20:00",
    service: "Dinner reservation (4 guests)",
    staffMember: "Evening team",
    parsingConfidence: 96,
    parseStatus: "success",
    reviewRequestStatus: "redirected",
    reviewRequestSentAt: "2026-03-17T23:00:00Z",
    reviewRequestOpenedAt: "2026-03-18T09:22:00Z",
    reviewRequestClickedAt: "2026-03-18T09:23:00Z",
    rating: 4,
    redirectedToGoogle: true,
    redirectedAt: "2026-03-18T09:23:45Z",
    createdAt: "2026-03-17T20:00:00Z",
  },
];

export const bellaVistaFeedback: FeedbackItem[] = [
  {
    id: "bv-fb-1",
    businessId: "demo-bella-vista",
    customerId: "bv-4",
    customerName: "Rachel Kim",
    customerPhone: "+1 212 555 0204",
    rating: 1,
    feedback:
      "Waited 45 minutes for our table despite having a reservation. When we finally sat down, two of our six orders were wrong. The waiter was dismissive when we pointed it out. Completely ruined our anniversary dinner.",
    status: "new",
    aiSuggestedReply:
      "Hi Rachel, I'm so sorry - this is genuinely awful and I'm embarrassed reading it. A 45-minute wait with a reservation, wrong orders, and a dismissive response from our team on your anniversary? That's the opposite of everything we stand for. I'd really like to speak with you personally. Please call me, Sofia, directly at (212) 555-0187. I want to make this right - and I mean that sincerely, not just as a business response. Thank you for taking the time to tell us.",
    aiReplies: {
      apologetic: "Hi Rachel, I'm so sorry - this is genuinely awful and I'm embarrassed reading it. A 45-minute wait with a reservation, wrong orders, and a dismissive response from our team on your anniversary? That's the opposite of everything we stand for. I'd really like to speak with you personally. Please call me, Sofia, directly at (212) 555-0187. I want to make this right - and I mean that sincerely, not just as a business response. Thank you for taking the time to tell us.",
      professional: "Hi Rachel, thank you for taking the time to share this. A reservation wait of 45 minutes, incorrect orders, and an inadequate response from our team is not acceptable - particularly on a special occasion. I would like to speak with you directly. Please contact me, Sofia, at (212) 555-0187 at your convenience. We take experiences like this very seriously and I would like the opportunity to make amends properly. - Bella Vista",
      personal: "Rachel - I'm mortified reading this. Your anniversary dinner, and we got it that wrong. The wait, the wrong orders, and then someone being dismissive on top of it? I'm so sorry. Please call me directly - (212) 555-0187, ask for Sofia. I'd like to make this right in a real way, not just with words. - Sofia",
    },
    createdAt: "2026-03-23T21:18:00Z",
  },
  {
    id: "bv-fb-2",
    businessId: "demo-bella-vista",
    customerId: "bv-7",
    customerName: "Carlos Mendez",
    customerPhone: "+1 212 555 0207",
    rating: 2,
    feedback:
      "The food was actually good but the service was very slow. We waited 30 minutes between courses. On a Saturday night it should be better managed. Won't be rushing back.",
    status: "in_progress",
    aiSuggestedReply:
      "Hi Carlos, thank you for being honest with us. I'm glad you enjoyed the food, but slow service on a Saturday is not good enough - you shouldn't be waiting 30 minutes between courses. We've been working on our pacing and I genuinely believe we're better than that experience suggested. I'd love to have you back and show you what a great night at Bella Vista looks like. Reply here or call us and I'll personally make sure your next visit is the experience you deserved. - Sofia",
    aiReplies: {
      apologetic: "Hi Carlos, thank you for being honest with us. I'm glad you enjoyed the food, but slow service on a Saturday is not good enough - you shouldn't be waiting 30 minutes between courses. We've been working on our pacing and I genuinely believe we're better than that experience suggested. I'd love to have you back and show you what a great night at Bella Vista looks like. Reply here or call us and I'll personally make sure your next visit is the experience you deserved. - Sofia",
      professional: "Hi Carlos, thank you for your feedback. We're pleased the food met expectations, however a 30-minute gap between courses is not the service standard we aim to deliver, particularly on a busy Saturday evening. We are actively reviewing our floor management to address this. We'd welcome the opportunity to host you again and demonstrate the level of service you should have received. - Bella Vista",
      personal: "Carlos - the food landing well but the pacing ruining it is probably the most frustrating thing, because you can see what we're capable of. I hear you. Come back, ask for Sofia, and I'll personally make sure the evening flows properly. That 30-minute gap shouldn't have happened. - Sofia",
    },
    internalNotes: "Replied via SMS. Waiting for customer response.",
    createdAt: "2026-03-21T23:25:00Z",
  },
  {
    id: "bv-fb-3",
    businessId: "demo-bella-vista",
    customerId: "bv-10",
    customerName: "Samantha Hoang",
    customerPhone: "+1 212 555 0210",
    rating: 2,
    feedback:
      "Pasta was overcooked and bland. Felt like it came out of a packet. Also, the bread brought at the start was cold. For these prices I expected much better.",
    status: "new",
    aiSuggestedReply:
      "Hi Samantha, I'm really sorry to hear this - overcooked pasta and cold bread is not what we serve, and I completely understand your disappointment, especially at our price point. I'd love to have you back so you can experience what our kitchen is actually capable of. Please come back as our guests - dinner for two on us. Just call (212) 555-0187 and ask for Sofia and I'll personally make sure everything is right. Thank you for the honest feedback.",
    aiReplies: {
      apologetic: "Hi Samantha, I'm really sorry to hear this - overcooked pasta and cold bread is not what we serve, and I completely understand your disappointment, especially at our price point. I'd love to have you back so you can experience what our kitchen is actually capable of. Please come back as our guests - dinner for two on us. Just call (212) 555-0187 and ask for Sofia and I'll personally make sure everything is right. Thank you for the honest feedback.",
      professional: "Hi Samantha, thank you for your candid feedback. Overcooked pasta and cold bread are not standards we accept, and the combination of these issues at our price point is understandable cause for disappointment. I'd welcome the opportunity to demonstrate what our kitchen can genuinely deliver. Please contact us at (212) 555-0187 to arrange a complimentary return visit. - Bella Vista",
      personal: "Samantha - pasta that tastes like a packet? Cold bread to start? I hope not, but the fact that's how it felt means something went wrong that night and that's on us. Come back as our guest, dinner for two on me. Call and ask for Sofia - I'll make sure it's everything it should have been the first time. - Sofia",
    },
    createdAt: "2026-03-19T23:48:00Z",
  },
];

export const bellaVistaAnalytics: AnalyticsData[] = [
  { month: "Oct 2025", sent: 52, completed: 17, redirected: 12, negativeCaught: 4, avgRating: 3.4 },
  { month: "Nov 2025", sent: 58, completed: 19, redirected: 13, negativeCaught: 5, avgRating: 3.5 },
  { month: "Dec 2025", sent: 71, completed: 22, redirected: 15, negativeCaught: 6, avgRating: 3.5 },
  { month: "Jan 2026", sent: 63, completed: 20, redirected: 14, negativeCaught: 5, avgRating: 3.6 },
  { month: "Feb 2026", sent: 55, completed: 18, redirected: 12, negativeCaught: 5, avgRating: 3.6 },
  { month: "Mar 2026", sent: 38, completed: 11, redirected: 8, negativeCaught: 3, avgRating: 3.7 },
];
